import Head from "next/head";
import Card from "@/components/card/card";
import { Game } from "@/model/game";
import { PlayerSummary } from "@/model/player";
import { getPlayerSummary } from "@/lib/api";

type Props = {
  summary?: PlayerSummary;
};

export default function Home(props: Props) {
  const title = "Most Played Games";

  const avatar = props.summary ? props.summary.avatarfull : "";
  const username = props.summary ? props.summary.personaname : "";

  const games: Game[] = [
    {
      name: "Counter-Strike: Global Offensive",
      playtime: 129000,
      lastplay: "2017-04-23",
      header: "https://cdn.akamai.steamstatic.com/steam/apps/730/header.jpg",
    },
    {
      name: "Dota 2",
      playtime: 310.2,
      lastplay: "2021-08-01",
      header: "https://cdn.akamai.steamstatic.com/steam/apps/570/header.jpg",
    },
    {
      name: "Grand Theft Auto V",
      playtime: 80,
      lastplay: "2022-06-11",
      header: "https://cdn.akamai.steamstatic.com/steam/apps/271590/header.jpg",
    },
    {
      name: "Rust",
      playtime: 5,
      lastplay: "2023-01-01",
      header: "https://cdn.akamai.steamstatic.com/steam/apps/252490/header.jpg",
    },
  ];

  return (
    <>
      <Head>
        <title>SteamEmbeds</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Card title={title} username={username} avatar={avatar} games={games} />
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const summary = await getPlayerSummary("76561198424303465");

  const props: Props = {
    summary: summary,
  };

  return { props: props };
}
